#ifndef VRP_UTILS_RANDOM_TRANSFORMEDDISTRIBUTION_HPP
#define VRP_UTILS_RANDOM_TRANSFORMEDDISTRIBUTION_HPP

#include "runtime/Config.hpp"

namespace vrp {
namespace utils {

/// Transforms values generated by another distribution.
template<typename Dist, typename Transformer>
class transformed_distribution {
  Dist dist;
  Transformer transformer;

public:
  transformed_distribution(Dist dist, Transformer transformer) :
    dist(dist), transformer(transformer) {}

  template<typename Gen>
  ANY_EXEC_UNIT auto operator()(Gen& generator) -> decltype(dist(generator)) {
    return transformer(dist(generator));
  }
};

template<typename Dist, typename Transformer>
transformed_distribution<Dist, Transformer> transformed(Dist dist, Transformer transfomer) {
  return transformed_distribution<Dist, Transformer>(dist, transfomer);
}

}  // namespace utils
}  // namespace vrp

#endif  // VRP_UTILS_RANDOM_TRANSFORMEDDISTRIBUTION_HPP
